name: Build (Sys)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-18.04' ]
        camlp-flag: [ '-usecamlp5' , '-usecamlp4' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install OCaml
        run: |
          sudo apt-get -o Acquire::Retries=30 update -q
          sudo apt-get -o Acquire::Retries=30 install ocaml-findlib camlp5 hevea || true
          sudo apt-get -o Acquire::Retries=30 install libnum-ocaml-dev || true
          sudo apt-get -o Acquire::Retries=30 install camlp4 || true
      - name: Build Coq
        run: |
          cd coq
          ./configure -local ${{ matrix.camlp-flag }}
          make TIMED=1
