name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        coq-version: [ '8.4' , '8.5' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq-version }}
          custom_script: |
            eval $(opam env)
            opam switch
            opam list
            uname -a
            sudo chmod -R a=u .
            cd coq
            ./configure -local
            make TIMED=1
